_extends: github-release-app:.github/release-drafter.yml
name-template: 'app-one-v$PATCH'
tag-template: 'app-one-v$PATCH'
tag-prefix: app-one-v
include-paths:
  - "app_one/lib/"
version-resolver:
  default: patch
