name: "Build gem"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    outputs:
      app-one-gem-name:
        value: ${{ jobs.build-app-one.outputs.app-one-gem-name-output }}
      app-two-gem-name:
        value: ${{ jobs.build-app-two.outputs.app-two-gem-name-output }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-app-one:
    runs-on: ubuntu-latest
    outputs:
      app-one-gem-name-output: ${{ steps.build-app-one-gem.outputs.GEM_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Get latest release
        id: latest_release
        run: |
          response=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases")
          latest_release=$(echo "$response" | jq -r 'sort_by(.published_at) | reverse | .[] | select(.draft == false) | select(.name | contains("app-one"))| .tag_name' | head -1)
          echo "Latest non-draft release is: $latest_release"

          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/releases"
          APP_ONE_TAG=$(curl -sSL -H "Authorization: token $TOKEN" "$API_URL" | jq -r 'sort_by(.published_at) | reverse | .[] | select(.draft == false) | select(.name | contains("app-one"))| .tag_name' | head -1)

          APP_TWO_TAG=$(curl -sSL -H "Authorization: token $TOKEN" "$API_URL" | jq -r 'sort_by(.published_at) | reverse | .[] | select(.draft == false) | select(.name | contains("app-two"))| .tag_name' | head -1)
          echo "Latest release tag for App1: $APP_ONE_TAG"
          APP_ONE_VERSION=$(echo $APP_ONE_TAG | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo app_one_version="$APP_ONE_VERSION" >> "$GITHUB_ENV"
          echo "Latest release tag for App2: $APP_TWO_TAG"
          APP_TWO_VERSION=$(echo $APP_TWO_TAG | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo app_two_version="$APP_TWO_VERSION" >> "$GITHUB_ENV"
        env:
          APP_ONE_VERSION: $APP_ONE_VERSION
          APP_TWO_VERSION: $APP_TWO_VERSION
      - name: Build AppOne Gem
        id: build-app-one-gem
        run: |
          export APP_ONE_VERSION=${{env.app_one_version}}
          gem build app_one.gemspec
          echo "::set-output name=GEM_NAME::$(basename app-one-${{env.app_one_version}}.gem)"
        working-directory: ./app_one
      - name: Upload Gem Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build-app-one-gem.outputs.GEM_NAME }}
          path: ./app_one/app-one-*.gem
  build-app-two:
    runs-on: ubuntu-latest
    outputs:
      app-two-gem-name-output: ${{ steps.build-app-two-gem.outputs.GEM_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Build AppTwo Gem
        id: build-app-two-gem
        # check that we can access the resolved version here
        run: |
          export APP_TWO_VERSION=${{env.app_two_version}}
          gem build app_one.gemspec
          echo "::set-output name=GEM_NAME::$(basename app-two-${{env.app_two_version}}.gem)"
          echo $RESOLVED_VERSION
        working-directory: ./app_two
      - name: Upload Gem Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build-app-two-gem.outputs.GEM_NAME }}
          path: ./app_two/app-two-*.gem
