name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: read

jobs:
  app_one:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-app-one.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  app_two:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-app-two.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
